// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bookmark-shortener/ent/bookmark"
	"bookmark-shortener/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BookmarkCreate is the builder for creating a Bookmark entity.
type BookmarkCreate struct {
	config
	mutation *BookmarkMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (bc *BookmarkCreate) SetTitle(s string) *BookmarkCreate {
	bc.mutation.SetTitle(s)
	return bc
}

// SetURL sets the "url" field.
func (bc *BookmarkCreate) SetURL(s string) *BookmarkCreate {
	bc.mutation.SetURL(s)
	return bc
}

// SetShortCode sets the "short_code" field.
func (bc *BookmarkCreate) SetShortCode(s string) *BookmarkCreate {
	bc.mutation.SetShortCode(s)
	return bc
}

// SetVisitCount sets the "visit_count" field.
func (bc *BookmarkCreate) SetVisitCount(i int) *BookmarkCreate {
	bc.mutation.SetVisitCount(i)
	return bc
}

// SetNillableVisitCount sets the "visit_count" field if the given value is not nil.
func (bc *BookmarkCreate) SetNillableVisitCount(i *int) *BookmarkCreate {
	if i != nil {
		bc.SetVisitCount(*i)
	}
	return bc
}

// SetCreatedAt sets the "created_at" field.
func (bc *BookmarkCreate) SetCreatedAt(t time.Time) *BookmarkCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BookmarkCreate) SetNillableCreatedAt(t *time.Time) *BookmarkCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BookmarkCreate) SetUpdatedAt(t time.Time) *BookmarkCreate {
	bc.mutation.SetUpdatedAt(t)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BookmarkCreate) SetNillableUpdatedAt(t *time.Time) *BookmarkCreate {
	if t != nil {
		bc.SetUpdatedAt(*t)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BookmarkCreate) SetID(u uuid.UUID) *BookmarkCreate {
	bc.mutation.SetID(u)
	return bc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (bc *BookmarkCreate) SetNillableID(u *uuid.UUID) *BookmarkCreate {
	if u != nil {
		bc.SetID(*u)
	}
	return bc
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (bc *BookmarkCreate) SetOwnerID(id uuid.UUID) *BookmarkCreate {
	bc.mutation.SetOwnerID(id)
	return bc
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (bc *BookmarkCreate) SetNillableOwnerID(id *uuid.UUID) *BookmarkCreate {
	if id != nil {
		bc = bc.SetOwnerID(*id)
	}
	return bc
}

// SetOwner sets the "owner" edge to the User entity.
func (bc *BookmarkCreate) SetOwner(u *User) *BookmarkCreate {
	return bc.SetOwnerID(u.ID)
}

// Mutation returns the BookmarkMutation object of the builder.
func (bc *BookmarkCreate) Mutation() *BookmarkMutation {
	return bc.mutation
}

// Save creates the Bookmark in the database.
func (bc *BookmarkCreate) Save(ctx context.Context) (*Bookmark, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BookmarkCreate) SaveX(ctx context.Context) *Bookmark {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BookmarkCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BookmarkCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BookmarkCreate) defaults() {
	if _, ok := bc.mutation.VisitCount(); !ok {
		v := bookmark.DefaultVisitCount
		bc.mutation.SetVisitCount(v)
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := bookmark.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := bookmark.DefaultUpdatedAt()
		bc.mutation.SetUpdatedAt(v)
	}
	if _, ok := bc.mutation.ID(); !ok {
		v := bookmark.DefaultID()
		bc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BookmarkCreate) check() error {
	if _, ok := bc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Bookmark.title"`)}
	}
	if _, ok := bc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Bookmark.url"`)}
	}
	if _, ok := bc.mutation.ShortCode(); !ok {
		return &ValidationError{Name: "short_code", err: errors.New(`ent: missing required field "Bookmark.short_code"`)}
	}
	if _, ok := bc.mutation.VisitCount(); !ok {
		return &ValidationError{Name: "visit_count", err: errors.New(`ent: missing required field "Bookmark.visit_count"`)}
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Bookmark.created_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Bookmark.updated_at"`)}
	}
	return nil
}

func (bc *BookmarkCreate) sqlSave(ctx context.Context) (*Bookmark, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BookmarkCreate) createSpec() (*Bookmark, *sqlgraph.CreateSpec) {
	var (
		_node = &Bookmark{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(bookmark.Table, sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID))
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := bc.mutation.Title(); ok {
		_spec.SetField(bookmark.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := bc.mutation.URL(); ok {
		_spec.SetField(bookmark.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := bc.mutation.ShortCode(); ok {
		_spec.SetField(bookmark.FieldShortCode, field.TypeString, value)
		_node.ShortCode = value
	}
	if value, ok := bc.mutation.VisitCount(); ok {
		_spec.SetField(bookmark.FieldVisitCount, field.TypeInt, value)
		_node.VisitCount = value
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(bookmark.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(bookmark.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := bc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookmark.OwnerTable,
			Columns: []string{bookmark.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_bookmarks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BookmarkCreateBulk is the builder for creating many Bookmark entities in bulk.
type BookmarkCreateBulk struct {
	config
	err      error
	builders []*BookmarkCreate
}

// Save creates the Bookmark entities in the database.
func (bcb *BookmarkCreateBulk) Save(ctx context.Context) ([]*Bookmark, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Bookmark, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookmarkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BookmarkCreateBulk) SaveX(ctx context.Context) []*Bookmark {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BookmarkCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BookmarkCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
