// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bookmark-shortener/ent/bookmark"
	"bookmark-shortener/ent/predicate"
	"bookmark-shortener/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BookmarkUpdate is the builder for updating Bookmark entities.
type BookmarkUpdate struct {
	config
	hooks    []Hook
	mutation *BookmarkMutation
}

// Where appends a list predicates to the BookmarkUpdate builder.
func (bu *BookmarkUpdate) Where(ps ...predicate.Bookmark) *BookmarkUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetTitle sets the "title" field.
func (bu *BookmarkUpdate) SetTitle(s string) *BookmarkUpdate {
	bu.mutation.SetTitle(s)
	return bu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (bu *BookmarkUpdate) SetNillableTitle(s *string) *BookmarkUpdate {
	if s != nil {
		bu.SetTitle(*s)
	}
	return bu
}

// SetURL sets the "url" field.
func (bu *BookmarkUpdate) SetURL(s string) *BookmarkUpdate {
	bu.mutation.SetURL(s)
	return bu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (bu *BookmarkUpdate) SetNillableURL(s *string) *BookmarkUpdate {
	if s != nil {
		bu.SetURL(*s)
	}
	return bu
}

// SetShortCode sets the "short_code" field.
func (bu *BookmarkUpdate) SetShortCode(s string) *BookmarkUpdate {
	bu.mutation.SetShortCode(s)
	return bu
}

// SetNillableShortCode sets the "short_code" field if the given value is not nil.
func (bu *BookmarkUpdate) SetNillableShortCode(s *string) *BookmarkUpdate {
	if s != nil {
		bu.SetShortCode(*s)
	}
	return bu
}

// SetVisitCount sets the "visit_count" field.
func (bu *BookmarkUpdate) SetVisitCount(i int) *BookmarkUpdate {
	bu.mutation.ResetVisitCount()
	bu.mutation.SetVisitCount(i)
	return bu
}

// SetNillableVisitCount sets the "visit_count" field if the given value is not nil.
func (bu *BookmarkUpdate) SetNillableVisitCount(i *int) *BookmarkUpdate {
	if i != nil {
		bu.SetVisitCount(*i)
	}
	return bu
}

// AddVisitCount adds i to the "visit_count" field.
func (bu *BookmarkUpdate) AddVisitCount(i int) *BookmarkUpdate {
	bu.mutation.AddVisitCount(i)
	return bu
}

// SetCreatedAt sets the "created_at" field.
func (bu *BookmarkUpdate) SetCreatedAt(t time.Time) *BookmarkUpdate {
	bu.mutation.SetCreatedAt(t)
	return bu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bu *BookmarkUpdate) SetNillableCreatedAt(t *time.Time) *BookmarkUpdate {
	if t != nil {
		bu.SetCreatedAt(*t)
	}
	return bu
}

// SetUpdatedAt sets the "updated_at" field.
func (bu *BookmarkUpdate) SetUpdatedAt(t time.Time) *BookmarkUpdate {
	bu.mutation.SetUpdatedAt(t)
	return bu
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (bu *BookmarkUpdate) SetOwnerID(id uuid.UUID) *BookmarkUpdate {
	bu.mutation.SetOwnerID(id)
	return bu
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (bu *BookmarkUpdate) SetNillableOwnerID(id *uuid.UUID) *BookmarkUpdate {
	if id != nil {
		bu = bu.SetOwnerID(*id)
	}
	return bu
}

// SetOwner sets the "owner" edge to the User entity.
func (bu *BookmarkUpdate) SetOwner(u *User) *BookmarkUpdate {
	return bu.SetOwnerID(u.ID)
}

// Mutation returns the BookmarkMutation object of the builder.
func (bu *BookmarkUpdate) Mutation() *BookmarkMutation {
	return bu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (bu *BookmarkUpdate) ClearOwner() *BookmarkUpdate {
	bu.mutation.ClearOwner()
	return bu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BookmarkUpdate) Save(ctx context.Context) (int, error) {
	bu.defaults()
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BookmarkUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BookmarkUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BookmarkUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bu *BookmarkUpdate) defaults() {
	if _, ok := bu.mutation.UpdatedAt(); !ok {
		v := bookmark.UpdateDefaultUpdatedAt()
		bu.mutation.SetUpdatedAt(v)
	}
}

func (bu *BookmarkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bookmark.Table, bookmark.Columns, sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Title(); ok {
		_spec.SetField(bookmark.FieldTitle, field.TypeString, value)
	}
	if value, ok := bu.mutation.URL(); ok {
		_spec.SetField(bookmark.FieldURL, field.TypeString, value)
	}
	if value, ok := bu.mutation.ShortCode(); ok {
		_spec.SetField(bookmark.FieldShortCode, field.TypeString, value)
	}
	if value, ok := bu.mutation.VisitCount(); ok {
		_spec.SetField(bookmark.FieldVisitCount, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedVisitCount(); ok {
		_spec.AddField(bookmark.FieldVisitCount, field.TypeInt, value)
	}
	if value, ok := bu.mutation.CreatedAt(); ok {
		_spec.SetField(bookmark.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := bu.mutation.UpdatedAt(); ok {
		_spec.SetField(bookmark.FieldUpdatedAt, field.TypeTime, value)
	}
	if bu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookmark.OwnerTable,
			Columns: []string{bookmark.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookmark.OwnerTable,
			Columns: []string{bookmark.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookmark.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BookmarkUpdateOne is the builder for updating a single Bookmark entity.
type BookmarkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookmarkMutation
}

// SetTitle sets the "title" field.
func (buo *BookmarkUpdateOne) SetTitle(s string) *BookmarkUpdateOne {
	buo.mutation.SetTitle(s)
	return buo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (buo *BookmarkUpdateOne) SetNillableTitle(s *string) *BookmarkUpdateOne {
	if s != nil {
		buo.SetTitle(*s)
	}
	return buo
}

// SetURL sets the "url" field.
func (buo *BookmarkUpdateOne) SetURL(s string) *BookmarkUpdateOne {
	buo.mutation.SetURL(s)
	return buo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (buo *BookmarkUpdateOne) SetNillableURL(s *string) *BookmarkUpdateOne {
	if s != nil {
		buo.SetURL(*s)
	}
	return buo
}

// SetShortCode sets the "short_code" field.
func (buo *BookmarkUpdateOne) SetShortCode(s string) *BookmarkUpdateOne {
	buo.mutation.SetShortCode(s)
	return buo
}

// SetNillableShortCode sets the "short_code" field if the given value is not nil.
func (buo *BookmarkUpdateOne) SetNillableShortCode(s *string) *BookmarkUpdateOne {
	if s != nil {
		buo.SetShortCode(*s)
	}
	return buo
}

// SetVisitCount sets the "visit_count" field.
func (buo *BookmarkUpdateOne) SetVisitCount(i int) *BookmarkUpdateOne {
	buo.mutation.ResetVisitCount()
	buo.mutation.SetVisitCount(i)
	return buo
}

// SetNillableVisitCount sets the "visit_count" field if the given value is not nil.
func (buo *BookmarkUpdateOne) SetNillableVisitCount(i *int) *BookmarkUpdateOne {
	if i != nil {
		buo.SetVisitCount(*i)
	}
	return buo
}

// AddVisitCount adds i to the "visit_count" field.
func (buo *BookmarkUpdateOne) AddVisitCount(i int) *BookmarkUpdateOne {
	buo.mutation.AddVisitCount(i)
	return buo
}

// SetCreatedAt sets the "created_at" field.
func (buo *BookmarkUpdateOne) SetCreatedAt(t time.Time) *BookmarkUpdateOne {
	buo.mutation.SetCreatedAt(t)
	return buo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (buo *BookmarkUpdateOne) SetNillableCreatedAt(t *time.Time) *BookmarkUpdateOne {
	if t != nil {
		buo.SetCreatedAt(*t)
	}
	return buo
}

// SetUpdatedAt sets the "updated_at" field.
func (buo *BookmarkUpdateOne) SetUpdatedAt(t time.Time) *BookmarkUpdateOne {
	buo.mutation.SetUpdatedAt(t)
	return buo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (buo *BookmarkUpdateOne) SetOwnerID(id uuid.UUID) *BookmarkUpdateOne {
	buo.mutation.SetOwnerID(id)
	return buo
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (buo *BookmarkUpdateOne) SetNillableOwnerID(id *uuid.UUID) *BookmarkUpdateOne {
	if id != nil {
		buo = buo.SetOwnerID(*id)
	}
	return buo
}

// SetOwner sets the "owner" edge to the User entity.
func (buo *BookmarkUpdateOne) SetOwner(u *User) *BookmarkUpdateOne {
	return buo.SetOwnerID(u.ID)
}

// Mutation returns the BookmarkMutation object of the builder.
func (buo *BookmarkUpdateOne) Mutation() *BookmarkMutation {
	return buo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (buo *BookmarkUpdateOne) ClearOwner() *BookmarkUpdateOne {
	buo.mutation.ClearOwner()
	return buo
}

// Where appends a list predicates to the BookmarkUpdate builder.
func (buo *BookmarkUpdateOne) Where(ps ...predicate.Bookmark) *BookmarkUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BookmarkUpdateOne) Select(field string, fields ...string) *BookmarkUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Bookmark entity.
func (buo *BookmarkUpdateOne) Save(ctx context.Context) (*Bookmark, error) {
	buo.defaults()
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BookmarkUpdateOne) SaveX(ctx context.Context) *Bookmark {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BookmarkUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BookmarkUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (buo *BookmarkUpdateOne) defaults() {
	if _, ok := buo.mutation.UpdatedAt(); !ok {
		v := bookmark.UpdateDefaultUpdatedAt()
		buo.mutation.SetUpdatedAt(v)
	}
}

func (buo *BookmarkUpdateOne) sqlSave(ctx context.Context) (_node *Bookmark, err error) {
	_spec := sqlgraph.NewUpdateSpec(bookmark.Table, bookmark.Columns, sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Bookmark.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bookmark.FieldID)
		for _, f := range fields {
			if !bookmark.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bookmark.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Title(); ok {
		_spec.SetField(bookmark.FieldTitle, field.TypeString, value)
	}
	if value, ok := buo.mutation.URL(); ok {
		_spec.SetField(bookmark.FieldURL, field.TypeString, value)
	}
	if value, ok := buo.mutation.ShortCode(); ok {
		_spec.SetField(bookmark.FieldShortCode, field.TypeString, value)
	}
	if value, ok := buo.mutation.VisitCount(); ok {
		_spec.SetField(bookmark.FieldVisitCount, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedVisitCount(); ok {
		_spec.AddField(bookmark.FieldVisitCount, field.TypeInt, value)
	}
	if value, ok := buo.mutation.CreatedAt(); ok {
		_spec.SetField(bookmark.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := buo.mutation.UpdatedAt(); ok {
		_spec.SetField(bookmark.FieldUpdatedAt, field.TypeTime, value)
	}
	if buo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookmark.OwnerTable,
			Columns: []string{bookmark.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookmark.OwnerTable,
			Columns: []string{bookmark.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Bookmark{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookmark.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
